const category = {
  alcohol: 'alcohol',
  beverage: 'beverage',
  forzen: 'forzen',
  candy: 'candy',
  ice: 'ice',
  instant: 'instant',
  lifeuse: 'lifeuse',
  medic: 'medic',
  milk: 'milk',
  noodle: 'noodle',
  onedate: 'onedate',
  snack: 'snack',
  tobacco: 'tobacco',
} as const;
